import { z } from "zod";

import {
    defineNotificationType,
    educationLevelOptions,
    healthOutcomeOptions,
    ministryProtocolOptions,
    raceColorOptions,
    screeningTestOptions,
    sexOptions,
    yesNoUnknownOptions,
    type NotificationSectionDefinition,
} from "@/features/notifications/definitions/shared"

const optionalTextSchema = z.string().optional();

const sections = [
  {
    id: "notification_data",
    title: "Dados Gerais",
    description: "Informações sobre a notificação e unidade notificadora.",
    columns: 3,
    fields: [
      {
        name: "tp_notification",
        label: "Tipo de Notificação",
        kind: "select",
        schema: z.string().default("2"),
        defaultValue: "2",
        options: [{ label: "Individual", value: "2" }],
      },
      {
        name: "ds_disease",
        label: "Agravo/doença",
        kind: "text",
        schema: z.string(),
        defaultValue: "ESQUISTOSSOMOSE",
      },
      {
        name: "ds_cid10",
        label: "Código (CID10)",
        kind: "text",
        schema: z.string().default("B 65.9"),
        defaultValue: "B 65.9",
      },
      {
        name: "dt_notification",
        label: "Data da Notificação",
        kind: "date",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_uf",
        label: "UF",
        kind: "text",
        schema: z.string().length(2, "UF obrigatória"),
        defaultValue: "",
      },
      {
        name: "notification_city",
        label: "Município de Notificação",
        kind: "text",
        schema: z.string().min(1, "Município obrigatório"),
        defaultValue: "",
      },
      {
        name: "notification_city_ibge_code",
        label: "Código (IBGE)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "health_unit_name",
        label: "Unidade de Saúde (ou outra fonte notificadora)",
        kind: "text",
        schema: z.string().min(1, "Unidade obrigatória"),
        defaultValue: "",
      },
      {
        name: "health_unit_code",
        label: "Código",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_first_symptoms",
        label: "Data dos Primeiros Sintomas",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "patient_data",
    title: "Notificação Individual",
    description: "Dados do paciente notificado.",
    columns: 3,
    fields: [
      {
        name: "patient_name",
        label: "Nome do Paciente",
        kind: "text",
        schema: z.string().min(1, "Nome obrigatório"),
        defaultValue: "",
      },
      {
        name: "patient_birth_date",
        label: "Data de Nascimento",
        kind: "date",
        schema: z.string().min(1, "Data de nascimento obrigatória"),
        defaultValue: "",
      },
      {
        name: "nu_age",
        label: "Idade",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_age_unit_hour",
        label: "Hora",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "tp_age_unit_day",
        label: "Dia",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "tp_age_unit_month",
        label: "Mês",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "tp_age_unit_year",
        label: "Ano",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: yesNoUnknownOptions,
      },
      {
        name: "tp_sex",
        label: "Sexo",
        kind: "select",
        schema: z.string().min(1, "Sexo obrigatório"),
        defaultValue: "",
        options: [
          { label: "Masculino", value: "M" },
          { label: "Feminino", value: "F" },
          { label: "Ignorado", value: "I" },
        ],
      },
      {
        name: "st_pregnant",
        label: "Gestante",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "1º Trimestre", value: "1" },
          { label: "2º Trimestre", value: "2" },
          { label: "3º Trimestre", value: "3" },
          { label: "Idade gestacional Ignorada", value: "4" },
          { label: "Não", value: "5" },
          { label: "Não se aplica", value: "6" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "tp_race_color",
        label: "Raça/Cor",
        kind: "select",
        schema: z.string().min(1, "Raça/Cor obrigatória"),
        defaultValue: "",
        options: [
          { label: "Branca", value: "1" },
          { label: "Preta", value: "2" },
          { label: "Amarela", value: "3" },
          { label: "Parda", value: "4" },
          { label: "Indígena", value: "5" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "tp_education_level",
        label: "Escolaridade",
        kind: "select",
        schema: z.string().min(1, "Escolaridade obrigatória"),
        defaultValue: "",
        options: [
          { label: "Analfabeto", value: "0" },
          { label: "1ª a 4ª série incompleta do EF", value: "1" },
          { label: "2ª série completa do EF", value: "2" },
          { label: "5ª a 8ª série incompleta do EF", value: "3" },
          { label: "Ensino fundamental completo", value: "4" },
          { label: "Ensino médio incompleto", value: "5" },
          { label: "Ensino médio completo", value: "6" },
          { label: "Educação superior incompleta", value: "7" },
          { label: "Educação superior completa", value: "8" },
          { label: "Ignorado", value: "9" },
          { label: "Não se aplica", value: "10" },
        ],
      },
      {
        name: "nu_sus_card",
        label: "Número do Cartão SUS",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "mother_name",
        label: "Nome da mãe",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "residence_data",
    title: "Dados de Residência",
    description: "Localização de residência do paciente.",
    columns: 3,
    fields: [
      {
        name: "residence_uf",
        label: "UF",
        kind: "text",
        schema: z.string().length(2, "UF obrigatória"),
        defaultValue: "",
      },
      {
        name: "residence_city",
        label: "Município de Residência",
        kind: "text",
        schema: z.string().min(1, "Município obrigatório"),
        defaultValue: "",
      },
      {
        name: "residence_city_ibge_code",
        label: "Código (IBGE)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_district",
        label: "Distrito",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_neighborhood",
        label: "Bairro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_street",
        label: "Logradouro (rua, avenida,...)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_street_code",
        label: "Código (Logradouro)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_number",
        label: "Número",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_complement",
        label: "Complemento (apto., casa, ...)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_geocampo1",
        label: "Geo campo 1",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_geocampo2",
        label: "Geo campo 2",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_reference_point",
        label: "Ponto de Referência",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_zipcode",
        label: "CEP",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "residence_phone",
        label: "(DDD) Telefone",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "tp_zone",
        label: "Zona",
        kind: "select",
        schema: z.string().min(1, "Obrigatório"),
        defaultValue: "9",
        options: [
          { label: "Urbana", value: "1" },
          { label: "Rural", value: "2" },
          { label: "Periurbana", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "st_resident_abroad",
        label: "País (se residente fora do Brasil)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "complementary_data",
    title: "Dados Complementares do Caso",
    description: "Informações adicionais sobre a investigação epidemiológica.",
    columns: 2,
    fields: [
      {
        name: "dt_investigation",
        label: "Data da Investigação",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "ds_occupation",
        label: "Ocupação",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "laboratory_data",
    title: "Dados do Laboratório",
    description: "Resultados de exames laboratoriais.",
    columns: 2,
    fields: [
      {
        name: "dt_coproscopy",
        label: "Data da Coproscopia",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_quantitative_analysis",
        label: "Análise Quantitativa",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "0 (zero)", value: "0" },
          { label: "1 (um) ou mais ovos", value: "1" },
        ],
      },
      {
        name: "st_qualitative_analysis",
        label: "Análise Qualitativa",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Não realizado", value: "3" },
        ],
      },
      {
        name: "st_other_exams",
        label: "OUTROS",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Positivo", value: "1" },
          { label: "Negativo", value: "2" },
          { label: "Não realizado", value: "3" },
        ],
      },
      {
        name: "ds_other_exams_specify",
        label: "Outros exames (especificar)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "treatment_data",
    title: "Tratamento",
    description: "Informações sobre o tratamento realizado.",
    columns: 2,
    fields: [
      {
        name: "st_treatment_done",
        label: "Fez Tratamento?",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Sim - Praziquantel", value: "1" },
          { label: "Sim - Oxamniquine", value: "2" },
          { label: "Não", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_treatment",
        label: "Data do Tratamento",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_treatment_reason_not_done",
        label: "Caso não tenha feito tratamento, qual o motivo?",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Contra Indicação", value: "1" },
          { label: "Recusa", value: "2" },
          { label: "Ausente", value: "3" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "st_result_verification_analysis",
        label: "Resultado de Análise de Verificação de Cura",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "0 (zero)", value: "0" },
          { label: "1 (um) ou mais ovos", value: "1" },
          { label: "Não realizado", value: "2" },
        ],
      },
      {
        name: "st_result_verification_samples",
        label: "Amostras Verificadas",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "1ª amostra", value: "1" },
          { label: "2ª amostra", value: "2" },
          { label: "3ª amostra", value: "3" },
        ],
      },
      {
        name: "dt_result_3a_sample",
        label: "Data do Resultado da 3ª amostra",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },
  {
    id: "infection_location",
    title: "Local Provável de Infecção",
    description: "Informações sobre o local onde a infecção provavelmente ocorreu.",
    columns: 2,
    fields: [
      {
        name: "tp_clinical_form",
        label: "Especificar Forma Clínica",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "",
        options: [
          { label: "Intestinal", value: "1" },
          { label: "Hepato Intestinal", value: "2" },
          { label: "Hepato Esplênica", value: "3" },
          { label: "Aguda", value: "4" },
          { label: "Outra (especificar)", value: "5" },
        ],
      },
      {
        name: "ds_clinical_form_other_specify",
        label: "Especificar",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_autochthonous_residence_municipality",
        label: "O caso é autóctone do município de residência?",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Indeterminado", value: "3" },
        ],
      },
      {
        name: "uf_infection",
        label: "UF",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "country_infection",
        label: "País",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "municipality_infection",
        label: "Município",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "municipality_infection_ibge_code",
        label: "Código (IBGE)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "district_infection",
        label: "Distrito",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "neighborhood_infection",
        label: "Bairro",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "property_name",
        label: "Nome da Propriedade (se área rural)",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "water_collection_name",
        label: "Nome da Coleção Hídrica",
        kind: "text",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "st_work_related_disease",
        label: "Doença Relacionada ao Trabalho",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Sim", value: "1" },
          { label: "Não", value: "2" },
          { label: "Ignorado", value: "9" },
        ],
      },
    ],
  },
  {
    id: "conclusion",
    title: "Conclusão",
    description: "Evolução do caso e dados de encerramento.",
    columns: 2,
    fields: [
      {
        name: "tp_case_evolution",
        label: "Evolução do Caso",
        kind: "select",
        schema: optionalTextSchema,
        defaultValue: "9",
        options: [
          { label: "Cura", value: "1" },
          { label: "Não Cura", value: "2" },
          { label: "Óbito por esquistossomose", value: "3" },
          { label: "Óbito por outras causas", value: "4" },
          { label: "Ignorado", value: "9" },
        ],
      },
      {
        name: "dt_death",
        label: "Data do Óbito",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
      {
        name: "dt_closure",
        label: "Data do Encerramento",
        kind: "date",
        schema: optionalTextSchema,
        defaultValue: "",
      },
    ],
  },

] as const satisfies readonly NotificationSectionDefinition[]

export const schistosomiasisNotificationDefinition = defineNotificationType({
  id: 5,
  slug: "schistosomiasis",
  label: "ESQUISTOSSOMOSE",
  description: `Caso CONFIRMADO: Todo indivíduo que apresente ovos viáveis de Schistosoma mansoni nas fezes ou em tecido submetido à biópsia.`,
  sections,
})
